# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NRSur Catalogs
author: NRSurCat Team
logo: https://raw.githubusercontent.com/nrsur-catalog/logo/main/nrsurcat_favicon.png

execute:
  execute_notebooks: 'off'

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/nrsur-catalog/nrsur-catalog.github.io  
  path_to_book: docs
  branch: main

html:
  use_issues_button: false
  use_repository_button: false
  favicon: https://raw.githubusercontent.com/nrsur-catalog/logo/main/nrsurcat_favicon.png




